# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hackathon' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for hackathon

  pod 'Firebase/Core', '~> 5.20.1'
  pod 'Firebase/Auth', '~> 5.20.1'
  pod 'Firebase/Firestore', '~> 5.20.1'
  pod 'Firebase/Storage', '~> 5.20.1'
  
end
